version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      # Install all dependencies (including dependencies for running tests)
      - npm install
  build:
    commands:
      # Use AWS SAM to package the application by using AWS CloudFormation
      - sam build --template template.yaml 
      - sam deploy --template-file template.yaml --s3-bucket aws-sam-cli-managed-default-samclisourcebucket-nqukhe41fq2 --stack-name test-CI-app
artifacts:
  files:
    - '**/*'