phases:
  install:
    runtime-versions:
      nodejs: 10

  build:
    commands:
      - sam build

  post_build:
    commands:
      - sam package --output-template-file packaged.yaml --s3-bucket codepipeline-ap-south-1-873493824052

artifacts:
  type: zip
  files:
    - packaged.yaml