version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - aws cloudformation package --template-file template.yaml --s3-bucket cd-demo-bucket-889715844992 --output-template-file outputSamTemplate.yaml
artifacts:
  type: zip
  files:
    - template.yaml
    - outputSamTemplate.yaml