version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-app2"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-nqukhe41fq2"
s3_prefix = "sam-app2"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

